apiVersion: v1
kind: Service
metadata:
  name: productui-svc
  namespace: shoppingportal
  labels:
    app: productui
spec:
  selector:
        app: productui   
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: my-http-port