apiVersion: apps/v1
kind: Deployment
metadata:
  name: productreviewms-deploy
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      zone: prod
      app: productreviewms 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        version: v1
        release: stable
        tier: be
        zone: prod
        managed-by: m2
        app: productreviewms
    spec:
      containers:
        - name: productreviewms-ctr
          image: metamagicglobal/productreviewservice_k8
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8082
          env:
          - name: MONO_HOST
            valueFrom:
              secretKeyRef: 
                name: mongosecret
                key: mongohost
          - name: MONO_PORT
            valueFrom:
              secretKeyRef: 
                name: mongosecret
                key: mongoport