apiVersion: v1
kind: Service
metadata:
  name: productreview-svc
  namespace: shoppingportal
spec:
  selector: 
    app: productreviewms
  ports:
  - protocol: TCP
    targetPort: 8082
    port: 80
    name: http
