apiVersion: apps/v1
kind: Deployment
metadata:
  name: productreview-deploy
  namespace: shoppingportal2
  labels:
    name: productreview
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productreviewms
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: productreviewms
        version: v1
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
    spec:
      serviceAccountName: productreviewms-sa   
      containers:
        - name: productreview-ctr
          image: metamagicglobal/productreviewms
          imagePullPolicy: Always
          ports:
          - containerPort: 8082