apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: shoppingportal
  labels:
      name: productms
spec:
  selector: 
    name: productms
  ports:
  - protocol: TCP
    targetPort: 8082
    port: 80
    name: http