apiVersion: apps/v1
kind: Deployment
metadata:
  name: productms-deploy
  namespace: shoppingportal
  labels:
     name: productms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productms
      zone: prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: productms
        version: v1
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
    spec:
      serviceAccountName: productms-sa
      containers:
        - name: productms-ctr
          image: metamagicglobal/productmswithoutdb
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
          env:
          - name: PRODUCTMS_DB_CONNECTION_URL
            valueFrom:
              secretKeyRef: 
                name: productmssecret
                key: mysqlconnectionurl
          - name: PRODUCTMS_DB_USER
            valueFrom:
              secretKeyRef: 
                name: productmssecret
                key: mysqluser
          - name: PRODUCTMS_DB_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: productmssecret
                key: mysqlpassword
          - name: PRODUCTMS_VERSION
            value: Product MS Version 1.0
---
apiVersion: v1
kind: Secret
metadata:
  name: productmssecret
  namespace: shoppingportal
type: Opaque
data:
  mysqlpassword: cm9vdA==
  mysqluser: cm9vdA==
  mysqlconnectionurl: amRiYzpteXNxbDovL215c3FsL3N5cwo=            