apiVersion: v1
kind: Service
metadata:
  name: productreviewservice
  namespace: shoppingportal
  labels:
    name: productreview  
spec:
  selector: 
    name: productreviewms
  ports:
  - protocol: TCP
    targetPort: 8082
    port: 80
    name: http