apiVersion: v1
kind: Service
metadata:
  name: k8uiworkshopservice
  namespace: shoppingportal
  labels:
    name: k8uiworkshop   
spec:
  selector: 
    name: k8uiworkshop
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
    name: http