apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "shoppingportalui-peer-policy"
  namespace: "shoppingportal"
spec:
  selector:
    matchLabels:
      app: shoppingportalui
  mtls:
    mode: STRICT
