apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-cmd-service
  namespace: shoppingportal
  labels:
    app: sp-cart-cmd-svc
spec:
  selector:
    app: sp-cart-cmd-svc
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
     name: http