#!/bin/bash -v
kubectl apply -f 5-App/shopping-ns.yaml
kubectl apply -f 5-App/mongo-secret.yaml
kubectl apply -f 5-App/mongo-ex-svc.yaml
kubectl apply -f 5-App/mongo-endpoints.yaml
kubectl apply -f 5-App/kafka-ex-svc.yaml
kubectl apply -f 5-App/user-k8s/
kubectl apply -f 5-App/product-k8s/
kubectl apply -f 5-App/ui-k8s/
kubectl apply -f 5-App/order-k8s/
kubectl apply -f 5-App/payment-k8s/
kubectl apply -f 5-App/productreview-k8s/
kubectl apply -f 5-App/ms.shopping.cart.aggregator.service/ms-k8-yml/
kubectl apply -f 5-App/ms.shopping.cart.cmd.service/k8-yml/
kubectl apply -f 5-App/ms.shopping.cart.query.service/k8-yml/
kubectl apply -f 5-App/ms.shopping.cart.enhancer.service/k8-yml/
kubectl apply -f 1-Traffic/shoppingportal-1-gw.yaml
kubectl apply -f 1-Traffic/ui-svc-vs.yaml
kubectl apply -f 1-Traffic/user-svc-vs.yaml
kubectl apply -f 1-Traffic/product-svc-vs.yaml
kubectl apply -f 1-Traffic/product-review-svc-vs.yaml
kubectl apply -f 1-Traffic/payment-virtualservice.yaml
kubectl apply -f 1-Traffic/order-svc-vs.yaml
kubectl apply -f 1-Traffic/shoppingportal-destination-rules.yml
kubectl apply -f 1-Traffic/ms-cart-cmd-vs.yaml
kubectl apply -f 1-Traffic/ms-cart-query-vs.yaml
kubectl apply -f 1-Traffic/zipkin-vs.yaml
