apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shoppingportal
  labels:
    app: order-svc
spec:
  selector:
    app: order-svc
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
     name: http