apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shoppingportal
  labels:
    app: product-svc
spec:
  selector:
    app: product-svc
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
     name: http