#!/bin/bash

echo "Mock Service : Un-Installations"
echo "4.1 Un-Install the Apps: (UI, Cart, Order, Payment)"

kubectl delete  --filename App/lambda-namespace.yaml

echo "4.2 Switch the Namespace to default"
kubectl config set-context $(kubectl config current-context) --namespace=default
