apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: shoppingportal
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/
    
