apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: shoppingportal
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: plaintext
  - port: 9999
    name: jmx
  selector:
    app: kafka
  type: ClusterIP
