---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: metamagic/zoo:k8
        imagePullPolicy: Always
        name: zookeeper
        ports:
        - containerPort: 2181
