
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: default
spec:
  secretName: ingress-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: ${DOMAIN_NAME}
  dnsNames:
  - ${DOMAIN_NAME}