apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sp-cart-query-deploy
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      zone: prod
      app: sp-cart-query-svc
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: sp-cart-query-svc
        version: v1
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
        app: sp-cart-query-svc
    spec:
      containers:
        - name: ms-sp-cart-query-deploy-ctr
          image: metamagic/ms-ms.shopping.cart.query.service:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080           
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"        