apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: shoppingportal
  labels:
    app: user-svc
spec:
  selector:
    app: user-svc
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
     name: http