apiVersion: v1
kind: Secret
metadata:
  name: ordersecret
  namespace: shoppingportal
type: Opaque
data:
  order_app_base_url: aHR0cDovL29yZGVyLXN2Yy9vcmRlcm1z
  shoppingcart_app_base_url: aHR0cDovL3Nob3BwaW5nY2FydC1zdmMvc2hvcHBpbmdjYXJ0bXM=