apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shoppingportalui-vs
  namespace: shoppingportal  
spec:
  gateways:
  - shoppingportal-gateway
  hosts:
   - "*"
  http:
  - match:
    - uri:
        prefix: /shoppingportal
      headers:
        user-agent:
          regex: ".*Firefox.*"
    route:
    - destination:
        host: shoppingportalui-svc.shoppingportal.svc.cluster.local
        subset: canary # match v2 only
        port:
          number: 80           
  - match:
    - uri:
        prefix: /shoppingportal
    route:
    - destination:
        host: shoppingportalui-svc.shoppingportal.svc.cluster.local
        subset: stable # match v1 only
        port:
          number: 80
