apiVersion: v1
kind: Service
metadata:
  name: shoppingcartui-svc
  namespace: shoppingportal
  labels:
    name: shoppingcartuisvc
spec:
  selector:
        app: shoppingcartui
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: my-http-port