apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sp-ui-deploy-1
  namespace: shoppingportal
spec:
  replicas: 1
  selector:
    matchLabels:
      zone: prod
      app: shoppingportalui
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: shoppingportalui
        version: v2
        release: stable
        tier: fe
        zone: prod
        managed-by: m2
        app: shoppingportalui
    spec:
      containers:
        - name: ms-sp-ui-deploy-ctr
          image: metamagic/ms-sp-ui:1.1 
          imagePullPolicy: Always
          ports:
          - containerPort: 80             

